# Generated by Django 5.2.5 on 2025-08-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikamai_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoword',
            name='word',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
