# Generated by Django 5.2.5 on 2025-08-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikamai_app', '0002_alter_videoword_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
