# Generated by Django 5.2.5 on 2025-09-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikamai_app', '0005_sentence_delete_sentencehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='user',
        ),
        migrations.RemoveField(
            model_name='signlanguagehistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videoword',
            name='video',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.DeleteModel(
            name='SignLanguageHistory',
        ),
        migrations.DeleteModel(
            name='SignLanguageVideo',
        ),
        migrations.DeleteModel(
            name='VideoWord',
        ),
    ]
